/** Canonical Human World isometric scale. All room assets and hit footprints use this contract. */
export const WORLD_SCALE = {
  tileWidth: 96,
  tileHeight: 48,
  elevationHeight: 24,
  avatarHeight: 82,
  wallHeight: 88,
  doorWidthTiles: 1.5,
  furniture: {
    chair: { footprint: [1, 1] as const, displayWidth: 58, height: 58 },
    stool: { footprint: [1, 1] as const, displayWidth: 58, height: 68 },
    table: { footprint: [1, 1] as const, displayWidth: 86, height: 62 },
    sideTable: { footprint: [1, 1] as const, displayWidth: 76, height: 58 },
    bench: { footprint: [2, 1] as const, displayWidth: 126, height: 70 },
    sofa: { footprint: [2, 1] as const, displayWidth: 132, height: 76 },
    lamp: { footprint: [1, 1] as const, displayWidth: 54, height: 116 },
    plant: { footprint: [1, 1] as const, displayWidth: 72, height: 76 },
    tallPlant: { footprint: [1, 1] as const, displayWidth: 82, height: 112 },
    flowerPlanter: { footprint: [2, 1] as const, displayWidth: 124, height: 82 },
    eventLight: { footprint: [1, 1] as const, displayWidth: 62, height: 112 },
    ropeBarrier: { footprint: [2, 0.5] as const, displayWidth: 112, height: 72 },
    communityBoard: { footprint: [2, 1] as const, displayWidth: 118, height: 112 },
    cafeCounter: { footprint: [3, 1.5] as const, displayWidth: 176, height: 112 },
    marketStall: { footprint: [3, 2] as const, displayWidth: 188, height: 142 },
    fountain: { footprint: [3, 3] as const, displayWidth: 220, height: 166 },
    divider: { footprint: [2, 0.5] as const, displayWidth: 112, height: 62 },
    djStage: { footprint: [4, 2.5] as const, displayWidth: 250, height: 152 },
    speaker: { footprint: [1.5, 1] as const, displayWidth: 100, height: 112 },
    rentableStorefront: { footprint: [3, 2] as const, displayWidth: 205, height: 146 },
    digitalBillboard: { footprint: [3, 1] as const, displayWidth: 180, height: 148 },
    displayStand: { footprint: [2, 1] as const, displayWidth: 128, height: 124 },
    eventCanopy: { footprint: [3, 3] as const, displayWidth: 220, height: 166 },
  },
} as const;
