begin;

create table if not exists public.profiles (
  id text primary key,
  username text not null unique,
  bio text,
  verification_status boolean not null default true,
  avatar_url text,
  xp integer not null default 0,
  level integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_internal_id check (id ~ '^user_[0-9a-f]{64}$'),
  constraint profiles_username check (username = 'Human_' || upper(right(id, 8))),
  constraint profiles_bio_length check (bio is null or char_length(bio) <= 280),
  constraint profiles_xp_nonnegative check (xp >= 0),
  constraint profiles_level_positive check (level >= 1)
);

create table if not exists public.rooms (
  id text primary key,
  name text not null,
  owner_id text references public.profiles(id) on delete restrict,
  type text not null,
  capacity integer not null default 20,
  is_public boolean not null default true,
  top text not null default '50%',
  left text not null default '50%',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rooms_id_format check (id ~ '^[a-z0-9][a-z0-9-]{0,63}$'),
  constraint rooms_name_length check (char_length(name) between 1 and 80 and name = btrim(name)),
  constraint rooms_type_format check (type ~ '^[a-z][a-z0-9-]{0,31}$'),
  constraint rooms_capacity check (capacity between 1 and 250)
);

create table if not exists public.avatar_appearances (
  user_id text primary key references public.profiles(id) on delete cascade,
  base_color integer not null,
  hair_color integer not null,
  outfit_color integer not null,
  accessory_color integer not null,
  hair text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint avatar_base_color check (base_color between 0 and 16777215),
  constraint avatar_hair_color check (hair_color between 0 and 16777215),
  constraint avatar_outfit_color check (outfit_color between 0 and 16777215),
  constraint avatar_accessory_color check (accessory_color between 0 and 16777215),
  constraint avatar_hair_style check (hair in ('short', 'wave', 'buzz'))
);

create table if not exists public.follows (
  follower_id text not null references public.profiles(id) on delete cascade,
  following_id text not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  constraint follows_no_self check (follower_id <> following_id)
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id text not null references public.profiles(id) on delete restrict,
  author_name text not null,
  content text not null,
  room_id text references public.rooms(id) on delete set null,
  room_name text,
  likes integer not null default 0,
  comments integer not null default 0,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint posts_author_name check (author_name = 'Human_' || upper(right(author_id, 8))),
  constraint posts_content_length check (char_length(content) between 1 and 2000 and content = btrim(content)),
  constraint posts_counts_nonnegative check (likes >= 0 and comments >= 0),
  constraint posts_room_pair check ((room_id is null) = (room_name is null))
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id text not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists follows_following_id_idx on public.follows(following_id);
create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists posts_author_id_idx on public.posts(author_id);
create index if not exists posts_room_id_idx on public.posts(room_id);
create index if not exists post_likes_user_id_idx on public.post_likes(user_id);
create index if not exists rooms_owner_id_idx on public.rooms(owner_id);

create or replace function public.refresh_human_world_post_likes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected_post_id bigint;
begin
  affected_post_id := coalesce(new.post_id, old.post_id);
  update public.posts
  set likes = (select count(*) from public.post_likes where post_id = affected_post_id)
  where id = affected_post_id;
  return coalesce(new, old);
end;
$$;

drop trigger if exists post_likes_refresh_count on public.post_likes;
create trigger post_likes_refresh_count after insert or delete on public.post_likes
for each row execute function public.refresh_human_world_post_likes();
revoke all on function public.refresh_human_world_post_likes() from public, anon, authenticated;

create or replace function public.set_human_world_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
revoke all on function public.set_human_world_updated_at() from public, anon, authenticated;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_human_world_updated_at();
drop trigger if exists rooms_set_updated_at on public.rooms;
create trigger rooms_set_updated_at before update on public.rooms
for each row execute function public.set_human_world_updated_at();
drop trigger if exists avatars_set_updated_at on public.avatar_appearances;
create trigger avatars_set_updated_at before update on public.avatar_appearances
for each row execute function public.set_human_world_updated_at();
drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at before update on public.posts
for each row execute function public.set_human_world_updated_at();

insert into public.rooms (id, name, owner_id, type, capacity, is_public, top, left)
values
  ('central-plaza', 'Central Plaza', null, 'plaza', 50, true, '48%', '50%'),
  ('lunas-cafe', 'Luna''s Cafe', null, 'cafe', 24, true, '68%', '76%'),
  ('human-gallery', 'Human Gallery', null, 'gallery', 30, true, '27%', '25%')
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.profiles force row level security;
alter table public.rooms enable row level security;
alter table public.rooms force row level security;
alter table public.avatar_appearances enable row level security;
alter table public.avatar_appearances force row level security;
alter table public.follows enable row level security;
alter table public.follows force row level security;
alter table public.posts enable row level security;
alter table public.posts force row level security;
alter table public.post_likes enable row level security;
alter table public.post_likes force row level security;

revoke all on table public.profiles, public.rooms, public.avatar_appearances,
  public.follows, public.posts, public.post_likes from anon, authenticated;
revoke all on sequence public.posts_id_seq from anon, authenticated;
grant all on table public.profiles, public.rooms, public.avatar_appearances,
  public.follows, public.posts, public.post_likes to service_role;
grant usage, select on sequence public.posts_id_seq to service_role;

commit;
